# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collector',
            old_name='ph_level',
            new_name='pH_level',
        ),
    ]
